missionNamespace setVariable ["primaryClasses", 
["SAA_CLASSES_RIFLEMAN",
"SAA_CLASSES_NURSE",
"SAA_CLASSES_MACHINEGUNNER",
"SAA_CLASSES_GRENADIER",
"SAA_CLASSES_ENGINEER",
"SAA_CLASSES_ATSPEC",
"SAA_CLASSES_MEDIC",
"SAA_CLASSES_MARKSMAN",
"SAA_CLASSES_SNIPER"], true];

missionNamespace setVariable ["secondaryClasses", 
["SAA_CLASSES_NA",
"SAA_CLASSES_GRENADIER",
"SAA_CLASSES_ENGINEER",
"SAA_CLASSES_ATSPEC",
"SAA_CLASSES_MEDIC",
"SAA_CLASSES_MARKSMAN"], true];